(()=>{
const q=(s,r=document)=>r.querySelector(s),qa=(s,r=document)=>[...r.querySelectorAll(s)];
const root=document.documentElement;
const store={get(k,d){try{const v=localStorage.getItem('novi_'+k);return v===null?d:JSON.parse(v)}catch{return d}},set(k,v){localStorage.setItem('novi_'+k,JSON.stringify(v))}};
const palette=['#129ee7','#7158e8','#15a57d','#f49a37','#ec5368','#df4ba5'];
function hexRgb(h){h=h.replace('#','');return `${parseInt(h.slice(0,2),16)},${parseInt(h.slice(2,4),16)},${parseInt(h.slice(4,6),16)}`}
function shade(hex,amt){let n=parseInt(hex.slice(1),16),r=Math.max(0,Math.min(255,(n>>16)+amt)),g=Math.max(0,Math.min(255,((n>>8)&255)+amt)),b=Math.max(0,Math.min(255,(n&255)+amt));return '#'+[r,g,b].map(x=>x.toString(16).padStart(2,'0')).join('')}
function applyAccent(c){root.style.setProperty('--novi-accent',c);root.style.setProperty('--novi-accent-dark',shade(c,-55));root.style.setProperty('--novi-accent-light',shade(c,35));root.style.setProperty('--novi-rgb',hexRgb(c));let st=q('#noviRuntimeStyle');if(!st){st=document.createElement('style');st.id='noviRuntimeStyle';document.head.appendChild(st)}st.textContent=`
.appbar,.drawerHead{background:linear-gradient(110deg,var(--novi-accent-dark),var(--novi-accent))!important}.welcome{background:linear-gradient(115deg,rgba(var(--novi-rgb),.10),rgba(var(--novi-rgb),.30),rgba(var(--novi-rgb),.58))!important}.progress,.heroCard{background:linear-gradient(120deg,var(--novi-accent-dark),var(--novi-accent))!important}.ring{border-top-color:var(--novi-accent)!important}.save,.start,.settingsNav button.sel,.profileMini{background:linear-gradient(90deg,var(--novi-accent-dark),var(--novi-accent))!important}.choice.on{border-color:var(--novi-accent)!important;color:var(--novi-accent-dark)!important;background:rgba(var(--novi-rgb),.10)!important}.switch.on{background:var(--novi-accent)!important}.appearancePreview{background:linear-gradient(135deg,var(--novi-accent-dark),var(--novi-accent))!important}.colorDot.runtimeOn{outline:3px solid var(--novi-accent);outline-offset:3px}.storage span{background:linear-gradient(90deg,var(--novi-accent-dark),var(--novi-accent))!important}
html.novi-dark .dash,html.novi-dark .settingsShell{background:#071725!important;color:#eaf6ff!important}html.novi-dark .card,html.novi-dark .option,html.novi-dark .choice,html.novi-dark .xbtn{background:#0d2435!important;color:#eaf6ff!important;border-color:#25435a!important}html.novi-dark .field input,html.novi-dark .field select,html.novi-dark select{background:#0a1e2d!important;color:#eaf6ff!important;border-color:#31526a!important}html.novi-dark .stat{background:#0d2435!important;color:#eaf6ff!important;border-color:#25435a!important}html.novi-dark .settingRow{border-color:#213b4d!important}html.novi-dark .settingsTop p,html.novi-dark .settingRow small,html.novi-dark .option small{color:#a8bfce!important}
html.novi-compact .card{padding:16px!important;margin-bottom:10px!important}html.novi-compact .settingRow{min-height:55px!important}html.novi-compact .option{padding:12px!important}html.novi-reduce *,html.novi-reduce *:before,html.novi-reduce *:after{animation:none!important;transition:none!important;scroll-behavior:auto!important}`}
function applyTheme(t){root.classList.remove('novi-dark');let dark=t==='dark'||(t==='auto'&&matchMedia('(prefers-color-scheme: dark)').matches);if(dark)root.classList.add('novi-dark')}
function applyFont(v){const map={small:'14px',medium:'16px',large:'19px'};root.style.fontSize=map[v]||'16px'}
function applyDensity(v){root.classList.toggle('novi-compact',v==='compact')}
function initAppearance(){const panel=q('[data-panel="appearance"]');if(!panel)return;const choices=qa('.choice',panel),theme=store.get('theme','light');choices.forEach((c,i)=>{c.classList.toggle('on',['light','dark','auto'][i]===theme);c.onclick=()=>{let v=['light','dark','auto'][i];store.set('theme',v);applyTheme(v);choices.forEach(x=>x.classList.remove('on'));c.classList.add('on')}});let accent=store.get('accent',palette[0]);qa('.colorDot',panel).forEach((d,i)=>{d.classList.toggle('runtimeOn',palette[i]===accent);d.onclick=()=>{accent=palette[i];store.set('accent',accent);applyAccent(accent);qa('.colorDot',panel).forEach(x=>x.classList.remove('runtimeOn'));d.classList.add('runtimeOn')}});const rows=qa('.settingRow',panel),fontSel=q('select',rows[0]);if(fontSel){const labels={small:'صغير',medium:'متوسط',large:'كبير'},cur=store.get('font','medium');[...fontSel.options].forEach(o=>{if(o.textContent.trim()===labels[cur])fontSel.value=o.value});fontSel.onchange=()=>{let txt=fontSel.options[fontSel.selectedIndex].textContent.trim(),v=txt==='صغير'?'small':txt==='كبير'?'large':'medium';store.set('font',v);applyFont(v)}}const reduce=q('.switch',rows[1]);if(reduce){let on=store.get('reduceMotion',false);reduce.classList.toggle('on',on);root.classList.toggle('novi-reduce',on);reduce.onclick=()=>{on=!on;reduce.classList.toggle('on',on);root.classList.toggle('novi-reduce',on);store.set('reduceMotion',on)}}
if(!q('#densityRuntime',panel)){let card=document.createElement('div');card.className='card';card.id='densityRuntime';card.innerHTML='<div class="settingRow"><div><b>كثافة العرض</b><small>اختر مساحة العناصر داخل الواجهة</small></div><select><option value="comfortable">مريحة</option><option value="compact">مدمجة</option></select></div>';panel.appendChild(card);let s=q('select',card);s.value=store.get('density','comfortable');s.onchange=()=>{store.set('density',s.value);applyDensity(s.value)}}}
}
function initPersistentSwitches(){qa('.settingsPanel').forEach(p=>qa('.switch',p).forEach((s,i)=>{if(p.dataset.panel==='appearance')return;let k=`switch_${p.dataset.panel}_${i}`,on=store.get(k,s.classList.contains('on'));s.classList.toggle('on',on);s.onclick=()=>{on=!on;s.classList.toggle('on',on);store.set(k,on);if(p.dataset.panel==='security'&&i===0&&on)alert('تم تفعيل قفل التطبيق على هذا الجهاز. عند ربط المصادقة الحقيقية سيستخدم Face ID / Touch ID.')}}))}
function initSelects(){qa('.settingsPanel select').forEach((s,i)=>{if(s.closest('[data-panel="language"]')||s.closest('[data-panel="appearance"]'))return;let k='select_'+(s.closest('.settingsPanel')?.dataset.panel||'x')+'_'+i,v=store.get(k,null);if(v!==null)s.value=v;s.onchange=()=>store.set(k,s.value)})}
function initStudy(){const p=q('[data-panel="study"]');if(!p)return;qa('.option',p).forEach((o,i)=>o.onclick=()=>{const keys=['goal','timer','review','days','quiet','plan'];const prompts=['اكتب هدفك اليومي (مثال: 3 شباتر أو ساعتان)','مدة جلسة التركيز بالدقائق','بعد كم يوم تريد المراجعة الذكية؟','اكتب أيام الدراسة المفضلة','اكتب ساعات الهدوء (مثال: 11م - 7ص)','اختر: هادئة / متوازنة / مكثفة'];let old=store.get('study_'+keys[i],'');let v=prompt(prompts[i],old);if(v!==null&&v.trim()){store.set('study_'+keys[i],v.trim());let sm=q('small',o);if(sm)sm.textContent='المحدد: '+v.trim()}}});qa('.option',p).forEach((o,i)=>{let v=store.get('study_'+['goal','timer','review','days','quiet','plan'][i],'');if(v&&q('small',o))q('small',o).textContent='المحدد: '+v})}
function initData(){const p=q('[data-panel="data"]');if(!p)return;qa('.option',p).forEach((o,i)=>o.onclick=()=>{if(i===0){localStorage.setItem('novi_backup',JSON.stringify({...localStorage,backupAt:new Date().toISOString()}));alert('تم إنشاء نسخة احتياطية محلية ✓')}else if(i===1){let v=!store.get('autosync',true);store.set('autosync',v);alert(v?'تم تشغيل المزامنة التلقائية':'تم إيقاف المزامنة التلقائية')}else if(i===2){alert('سلة المهملات فارغة حالياً.')}else{const data=JSON.stringify({...localStorage},null,2),blob=new Blob([data],{type:'application/json'}),a=document.createElement('a');a.href=URL.createObjectURL(blob);a.download='NoviStudy-data.json';a.click();setTimeout(()=>URL.revokeObjectURL(a.href),1000)}})}
function initHelp(){const p=q('[data-panel="help"]');if(!p)return;qa('.option',p).forEach((o,i)=>o.onclick=()=>alert(['سيتم فتح قناة التواصل عند ربط بريد الدعم.','تم تجهيز نموذج الإبلاغ عن المشاكل للمرحلة القادمة.','تم حفظ رغبتك في اقتراح ميزة.','مركز المساعدة قيد التجهيز.'][i]))}
function initAbout(){const p=q('[data-panel="about"]');if(!p)return;qa('.settingRow',p).forEach((r,i)=>{if(i>0)r.style.cursor='pointer';if(i===1)r.onclick=()=>alert('سياسة الخصوصية ستظهر هنا عند إضافة النص النهائي.');if(i===2)r.onclick=()=>alert('شروط الاستخدام ستظهر هنا عند إضافة النص النهائي.');if(i===3)r.onclick=()=>alert('التراخيص ستظهر هنا عند إضافة قائمة المكتبات المستخدمة.')});const d=q('.dangerBtn',p);if(d)d.onclick=()=>{if(confirm('هل أنت متأكد؟ سيؤدي هذا إلى حذف بيانات NoviStudy المحفوظة على هذا الجهاز.')){Object.keys(localStorage).filter(k=>k.startsWith('novi')).forEach(k=>localStorage.removeItem(k));location.reload()}}}
function boot(){applyAccent(store.get('accent',palette[0]));applyTheme(store.get('theme','light'));applyFont(store.get('font','medium'));applyDensity(store.get('density','comfortable'));root.classList.toggle('novi-reduce',store.get('reduceMotion',false));initAppearance();initPersistentSwitches();initSelects();initStudy();initData();initHelp();initAbout();/* اللغة عمداً لا نغيّر اتجاه الصفحة أو النصوص حتى لا تتضرر الواجهة الحالية. */}
if(document.readyState==='loading')document.addEventListener('DOMContentLoaded',boot);else boot();
})();